version: "3.9"
services:
  mongo-server:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  server:
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo-server
